kubectl: https://dl.k8s.io/v1.20.0/kubernetes-client-linux-amd64.tar.gz
kustomize: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.1/kustomize_v3.8.1_linux_amd64.tar.gz
oc: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.14/openshift-client-linux-4.7.14.tar.gz
openshift-install: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.14/openshift-install-linux-4.7.14.tar.gz
