kubectl: https://dl.k8s.io/v1.15.0/kubernetes-client-linux-amd64.tar.gz
kustomize: https://github.com/kubernetes-sigs/kustomize/releases/download/v2.1.0/kustomize_2.1.0_linux_amd64
oc: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.11/openshift-client-linux-4.1.11.tar.gz
openshift-install: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.11/openshift-install-linux-4.1.11.tar.gz
