#!/bin/bash

# set -x
set -e

# Skip the config file name argument.
shift

PULL_SECRET=$(cat ${HOME}/.kni/pull-secret.json)
SSH_PUB_KEY=$(cat ${HOME}/.kni/id_rsa.pub)

cat - | sed \
    -e "s|PULL_SECRET|\'${PULL_SECRET}\'|" \
    -e "s|SSH_PUB_KEY|${SSH_PUB_KEY}|"
