---
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  namespace: openshift-image-registry
  finalizers:
  - imageregistry.operator.openshift.io/finalizer
spec:
  managementState: Managed
  storage:
    pvc:
      claim: image-registry-storage
  logging: 2
  replicas: 1
