apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: .*
  namespace: openshift-machine-api
spec:
  providerSpec:
    value:
      apiVersion: libvirtproviderconfig.openshift.io/v1beta1
      domainMemory: 12288
      domainVcpu: 4
