apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  overrides:
    - kind: DaemonSet
      name: cluster-node-tuning-operator
      namespace: openshift-cluster-node-tuning-operator
      unmanaged: true
