apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  overrides:
  - group: apps
    kind: Deployment
    name: cluster-node-tuning-operator
    namespace: openshift-cluster-node-tuning-operator
    unmanaged: true
    version: v1
