apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: realtime
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Openshift node optimized for deterministic performance at the cost of increased power consumption, focused on low latency network performance
      include=openshift-node

      [cpu]
      force_latency=1
      governor=performance
      energy_perf_bias=performance
      min_perf_pct=100

      [vm]
      transparent_hugepages=never

      [sysctl]
      net.core.busy_read=50
      net.core.busy_poll=50
      net.ipv4.tcp_fastopen=3
      kernel.numa_balancing=0
      # ktune sysctl settings for rhel6 servers, maximizing i/o throughput
      #
      # Minimal preemption granularity for CPU-bound tasks:
      # (default: 1 msec#  (1 + ilog(ncpus)), units: nanoseconds)
      kernel.sched_min_granularity_ns=10000000

      # If a workload mostly uses anonymous memory and it hits this limit, the entire
      # working set is buffered for I/O, and any more write buffering would require
      # swapping, so it's time to throttle writes until I/O can catch up.  Workloads
      # that mostly use file mappings may be able to use even higher values.
      #
      # The generator of dirty data starts writeback at this percentage (system default
      # is 20%)
      vm.dirty_ratio=10

      # Start background writeback (via writeback threads) at this percentage (system
      # default is 10%)
      vm.dirty_background_ratio=3

      # The swappiness parameter controls the tendency of the kernel to move
      # processes out of physical memory and onto the swap disk.
      # 0 tells the kernel to avoid swapping processes out of physical memory
      # for as long as possible
      # 100 tells the kernel to aggressively swap processes out of physical memory
      # and move them to swap cache
      vm.swappiness=10

      # The total time the scheduler will consider a migrated process
      # "cache hot" and thus less likely to be re-migrated
      # (system default is 500000, i.e. 0.5 ms)
      kernel.sched_migration_cost_ns=5000000

      [bootloader]
      cmdline=skew_tick=1
    name: openshift-node-network-latency

  - data: |
      [main]
      summary=Optimize systems running OpenShift realtime nodes
      include=openshift-node-network-latency

      [variables]
      # User is responsible for updating variables.conf with variable content such as isolated_cores=X-Y
      include = /etc/realtime_vars.conf
      isolated_cores_assert_check = \\${isolated_cores}
      # Fail if isolated_cores are not set
      assert1=${f:assertion_non_equal:isolated_cores are set:${isolated_cores}:${isolated_cores_assert_check}}

      # Non-isolated cores cpumask including offline cores
      not_isolated_cpumask = ${f:cpulist2hex_invert:${isolated_cores}}
      isolated_cores_expanded=${f:cpulist_unpack:${isolated_cores}}
      isolated_cpumask=${f:cpulist2hex:${isolated_cores_expanded}}
      isolated_cores_online_expanded=${f:cpulist_online:${isolated_cores}}

      # Fail if isolated_cores contains CPUs which are not online
      assert2=${f:assertion:isolated_cores contains online CPU(s):${isolated_cores_expanded}:${isolated_cores_online_expanded}}

      [selinux]
      avc_cache_threshold=8192

      [net]
      nf_conntrack_hashsize=131072

      [sysctl]
      net.ipv4.ip_forward=1
      kernel.pid_max=>131072
      net.netfilter.nf_conntrack_max=1048576
      net.ipv4.neigh.default.gc_thresh1=8192
      net.ipv4.neigh.default.gc_thresh2=32768
      net.ipv4.neigh.default.gc_thresh3=65536
      net.ipv6.neigh.default.gc_thresh1=8192
      net.ipv6.neigh.default.gc_thresh2=32768
      net.ipv6.neigh.default.gc_thresh3=65536
      net.ipv4.tcp_fastopen=3
      fs.inotify.max_user_watches=65536
      kernel.hung_task_timeout_secs = 600
      kernel.nmi_watchdog = 0
      kernel.sched_rt_runtime_us = -1
      vm.stat_interval = 10
      kernel.timer_migration = 0
      vm.nr_hugepages=${hugepage_num}

      [sysfs]
      /sys/module/nvme_core/parameters/io_timeout=4294967295
      /sys/module/nvme_core/parameters/max_retries=10
      /sys/bus/workqueue/devices/writeback/cpumask = ${not_isolated_cpumask}
      /sys/devices/virtual/workqueue/cpumask = ${not_isolated_cpumask}
      /sys/devices/system/machinecheck/machinecheck*/ignore_ce = 1

      [bootloader]
      cmdline_realtime=+isolcpus=${isolated_cores} intel_pstate=disable nosoftlockup nmi_watchdog=0 audit=0 mce=off kthread_cpus=0 irqaffinity=0 skew_tick=1 processor.max_cstate=1 idle=poll intel_idle.max_cstate=0 intel_pstate=disable intel_iommu=off default_hugepagesz=\${hugepage_size_default} hugepagesz=\${hugepage_size} hugepages=\${hugepage_num} nohz=on nohz_full=\${isolated_cores} rcu_nocbs=\${isolated_cores}

      [scheduler]
      isolated_cores=${isolated_cores}

    name: openshift-realtime-node
  recommend:
  - priority: 30
    profile: openshift-realtime-node
    match:
    - label: node-role.kubernetes.io/worker-ran
