apiVersion: v1
kind: InstallConfig
metadata:
  name: cluster
platform:
  none: {}
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 1
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
