---
# copied from https://github.com/kubevirt/kubevirt/releases/download/v0.18.1/kubevirt-cr.yaml
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  imagePullPolicy: IfNotPresent