apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sriovnetworknodepolicies.sriovnetwork.openshift.io
spec:
  group: sriovnetwork.openshift.io
  names:
    kind: SriovNetworkNodePolicy
    listKind: SriovNetworkNodePolicyList
    plural: sriovnetworknodepolicies
    singular: sriovnetworknodepolicy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            deviceType:
              enum:
              - netdevice
              - vfio-pci
              type: string
            isRdma:
              type: boolean
            mtu:
              format: int64
              maximum: 9000
              minimum: 1
              type: integer
            nicSelector:
              properties:
                deviceID:
                  type: string
                pfNames:
                  items:
                    type: string
                  type: array
                rootDevices:
                  items:
                    type: string
                  type: array
                vendor:
                  enum:
                  - "8086"
                  - 15b3
                  type: string
              type: object
            nodeSelector:
              additionalProperties:
                type: string
              type: object
            numVfs:
              format: int64
              minimum: 0
              type: integer
            priority:
              format: int64
              maximum: 99
              minimum: 0
              type: integer
            resourceName:
              type: string
          required:
          - resourceName
          - nodeSelector
          - numVfs
          - nicSelector
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
