apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  overrides:
  - group: apps
    kind: Deployment
    name: cluster-node-tuning-operator
    namespace: openshift-cluster-node-tuning-operator
    unmanaged: true
    version: v1
[root@vip 02_cluster-addons]# cat 05_tuning/01_disable_tuning_deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-node-tuning-operator
  namespace: openshift-cluster-node-tuning-operator
spec:
  replicas: 0
