bases:
- ../../../profiles/production.baremetal/02_cluster-addons
resources:
- 00_config-ran/00_realtime-configmap.yaml
patches:
- 02_ptp-daemonset/configmap.yaml
patchesJson6902:
- path: downscale-ingress-replicas.patch.yaml
  target:
    group: operator.openshift.io
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    version: v1
- path: worker-node-label.patch.yaml
  target:
    version: v1
    kind: Node
    name: testing-worker-0
