bases:
- ../../../profiles/production.baremetal/02_cluster-addons
patches:
- 02_ptp-daemonset/configmap.yaml
- 03_storage/00_storage.patch.yaml
patchesJson6902:
- path: downscale-ingress-replicas.patch.yaml
  target:
    group: operator.openshift.io
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    version: v1
