apiVersion: v1
baseDomain: aws.edge-sites.net
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: site-01
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"0123456789=","email":"user@exampe.com"},"quay.io":{"auth":"0123456789=","email":"user@example.com"},"registry.connect.redhat.com":{"auth":"0123456789","email":"user@example.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDo8udAzagmr4f6yoWhzsDnu3x0AqigToYDewN1iy2FLaZGK2qgZ1WQ4MUZGXoYQj5AaRTSQes0W8n0nKjhHtPwsqPvMyhhVUgm919WBhVHd8SGEA2eDmJx1WDPuiz5yk72iqcbl8l3Gduew+8EBdEtioawQIVg8DNjaTlc1NQ0qw== user@example.com
