apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker-rt
  namespace: kube-system
spec:
  machineConfigSelector:
    matchLabels:
      "machineconfiguration.openshift.io/role": "worker-rt"
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-rt: ""
