#!/bin/bash

#set -x
set -e

# If DRY_RUN=true, creates and modifies the installer manifests, but stops
# right before actually creating the cluster.
DRY_RUN=${DRY_RUN:-false}
# Log level passed through to the openshift-installer
LOG_LEVEL=${LOG_LEVEL:-debug}
# If PUSH_MODE=true, perfoms Day 2 operations (01_cluster-addons, 02_services)
# by pushing the respective manifests to the remote cluster.
# If PUSH_MODE=false, assumes the remote cluster will pull in Day 2 config
# changes itself.
PUSH_MODE=${PUSH_MODE:-false}
# Directory where secrets, binaries, and site config dirs are stored.
WORK_DIR=${WORK_DIR:-$HOME/.kni}

BLUEPRINT_DIR=$(dirname "$(dirname "$(readlink -f "$0")")")

SITE_CONFIG=$1
SITE_NAME=$(basename ${SITE_CONFIG})

# do some sanity checking
if [ $# -ne 1 ]; then
    1>&2 echo "Creates a new site from the specified blueprint and site-config.

Usage: $(basename $0) <site_config>

    <site_config>   directory containing the site's configs"
    exit 1
fi

if [ ! -d ${SITE_CONFIG} ]; then
    1>&2 echo "Site config dir ${SITE_CONFIG} does not exist."
    exit 1
fi

if [ ! -f ${WORK_DIR}/pull-secret.json ]; then
    1>&2 echo "No pull-secret.json found in ${WORK_DIR}."
    exit 1
fi

if [ ! -f ${WORK_DIR}/id_rsa.pub ]; then
    1>&2 echo "No SSH public key (id_rsa.pub) found in ${WORK_DIR}. Generating keypair."
    ssh-keygen -b 2048 -f ${WORK_DIR}/id_rsa -C user@example.com -q -N ""
fi

# look up profile used by the site to be deployed
PROFILE=$(grep -Eoh "profiles/([A-Za-z0-9.-])+" ${SITE_CONFIG}/00_install-config/*)
PROFILE=${PROFILE##*/}

# binaries are installed in ${WORK_DIR}/${SITE_NAME}
BINARIES_DIR=${WORK_DIR}/${SITE_NAME}
INSTALLER=${BINARIES_DIR}/openshift-install

KUSTOMIZE=${BINARIES_DIR}/kustomize
MAX_RETRIES=${MAX_RETRIES:-10}
RETRY_TIME=${RETRY_TIME:-30}

# enable kustomize plugins and no reorder
KUSTOMIZE_FLAGS="--enable_alpha_plugins --reorder none"
export XDG_CONFIG_HOME=${BLUEPRINT_DIR}/tools

# lookup any deployment overrides
RELEASE_IMAGE_OVERRIDE=$(grep -Eh "releaseImageOverride" ${SITE_CONFIG}/00_install-config/site-config.yaml) || true
RELEASE_IMAGE_OVERRIDE=${RELEASE_IMAGE_OVERRIDE#*: }
if [[ "${RELEASE_IMAGE_OVERRIDE}" != "" ]]; then
    export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=${RELEASE_IMAGE_OVERRIDE}
fi
export TF_VAR_libvirt_master_memory=8192
export TF_VAR_libvirt_master_vcpu=4

# generate openshift-install manifests based on phase '00_install-config'
mkdir -p ${WORK_DIR}/${SITE_NAME}
${KUSTOMIZE} build ${KUSTOMIZE_FLAGS} ${SITE_CONFIG}/00_install-config > ${WORK_DIR}/${SITE_NAME}/install-config.yaml
${INSTALLER} create manifests --dir=${WORK_DIR}/${SITE_NAME} --log-level ${LOG_LEVEL}

# create virtual base dir '00_cluster' for phase '01_cluster-mods' kustomization
pushd ${WORK_DIR}/${SITE_NAME} > /dev/null
echo "resources:" > kustomization.yaml
for f in $(ls manifests/*.yaml manifests/*.yml openshift/*.yaml); do
    echo "- $f" >> kustomization.yaml
done
popd > /dev/null
ln -sfn ${WORK_DIR}/${SITE_NAME} ${BLUEPRINT_DIR}/base/00_cluster

# update openshift-install manifests based on phase '01_cluster-mods' kustomization
${KUSTOMIZE} build ${KUSTOMIZE_FLAGS} ${SITE_CONFIG}/01_cluster-mods \
    | ${BLUEPRINT_DIR}/tools/modify_installer_manifests --dir=${WORK_DIR}/${SITE_NAME}

function apply_kustomize {
    echo "Applying customizations for $1"
    output=$(${KUSTOMIZE} build ${KUSTOMIZE_FLAGS} $1)
    if [ -z "$output" ]; then
        echo "No customizations to apply!"
    else
        for i in $(seq 1 $MAX_RETRIES); do
            echo "$output" | ${BINARIES_DIR}/kubectl apply -f - && break
            sleep ${RETRY_TIME}
        done
    fi
}

# create the cluster, unless $DRY_RUN has been set to true
if [ "$DRY_RUN" = false ]; then
    ${INSTALLER} create cluster --dir=${WORK_DIR}/${SITE_NAME} --log-level ${LOG_LEVEL}
    if ${INSTALLER} wait-for &> /dev/null; then
        ${INSTALLER} wait-for install-complete --dir=${WORK_DIR}/${SITE_NAME} --log-level ${LOG_LEVEL}
        echo "Installation complete!"
    fi

    if [ "$PUSH_MODE" = true ]; then
        export KUBECONFIG=${WORK_DIR}/${SITE_NAME}/auth/kubeconfig
        apply_kustomize ${SITE_CONFIG}/02_cluster-addons
        apply_kustomize ${SITE_CONFIG}/03_services
    fi
fi
