#!/bin/bash

#set -x
set -e

: "${WORK_DIR:=$HOME/.kni}"

if [ $# -ne 1 ]; then
    1>&2 echo "Fetches a blueprint's requirements (using the path specified on first argument).

Usage: $(basename $0) /path/to/site (relative to the current directory)"
    exit 1
fi

# check if requirements path exist
REQUIREMENTS_PATH="$(pwd)/$1/requirements.yaml"
if [ ! -e "${REQUIREMENTS_PATH}" ]; then
    1>&2 echo "Filename $REQUIREMENTS_PATH does not exist"
    exit 1
fi

# extract site name
SITE_NAME=$(basename $1)
mkdir -p "${WORK_DIR}/${SITE_NAME}"

function build_openshift-install {
# Build an openshift-install binary from source.
# URL refers to the git repo to clone from.
# REF is the git ref to checkout.
    local URL=$1
    local REF=$2

    TMP_DIR=$(mktemp -d)
    pushd "$TMP_DIR" > /dev/null
    export GOPATH=${TMP_DIR}/go
    mkdir -p "${GOPATH}/src/github.com/openshift"
    cd "${GOPATH}/src/github.com/openshift"
    git clone "${URL}"
    cd installer
    git checkout ${REF}
    TAGS=libvirt hack/build.sh
    mv bin/openshift-install ${WORK_DIR}/${SITE_NAME}/openshift-install
    popd > /dev/null
    /bin/rm -rf "$TMP_DIR"
}

function build_kustomize {
# Build a kustomize binary from source.
# URL refers to the git repo to clone from.
# REF is the git ref to checkout.
    local URL=$1
    local REF=$2

    TMP_DIR=$(mktemp -d)
    pushd "$TMP_DIR" > /dev/null
    mkdir ${TMP_DIR}/go
    GOPATH=${TMP_DIR}/go go get -v sigs.k8s.io/kustomize
    mv go/bin/kustomize ${WORK_DIR}/${SITE_NAME}/kustomize
    popd > /dev/null
    /bin/rm -rf "$TMP_DIR"
}

function fetch_requirement {
# Fetches the given binary (it can be openshift-install, oc, kubectl and
# kustomize).
# BINARY is the key of an entry in "requirements.yaml". It will be used
# to extract the specific binary from the specified url.
# URL and REF are parsed from the value in "requirements.yaml", which is
# assumed to be in "go-getter" format.
# (https://github.com/hashicorp/go-getter)
    local BINARY=$1
    local URL=${2%\?*}
    local REF=${2#*\?ref=}

    # check if the binary already exists
    if [ -f "${WORK_DIR}/${SITE_NAME}/${BINARY}" ]; then
        1>&2 echo "Using existing ${WORK_DIR}/${SITE_NAME}/${BINARY}."
    else
        case "${URL}" in
            *.tar.gz )
                # extract tar.gz if exists
                FILE_NAME=$(basename ${URL})

                1>&2 echo "Pulling ${FILE_NAME} tarball from ${URL}."
                TMP_DIR=$(mktemp -d)
                pushd "$TMP_DIR" > /dev/null

                curl -L ${URL} -o ${FILE_NAME}
                tar -xf ${FILE_NAME}

                # find the binary with the specified name and move it
                BINARY_PATH=$(find ./ -name ${BINARY} -print -quit)
                if [ ! -e "${BINARY_PATH}" ]; then
                    echo "${BINARY} not found in ${FILE_NAME} tarball"
                    exit
                fi
                mv ${BINARY_PATH} ${WORK_DIR}/${SITE_NAME}/${BINARY}
                popd > /dev/null
                /bin/rm -rf "$TMP_DIR"
                ;;
            *.git )
                1>&2 echo "Building ${BINARY} from ${URL}."
                local func_name="build_${BINARY}"
                $func_name ${URL} ${REF}
                ;;
            * )
                1>&2 echo "Pulling ${BINARY} binary from ${URL}."
                curl -L ${URL} -o ${WORK_DIR}/${SITE_NAME}/${BINARY}
                chmod a+x ${WORK_DIR}/${SITE_NAME}/${BINARY}
                ;;
        esac
    fi
}


# Parses lines in "requirements.yaml" to fetch KV-pairs of
# profile names (or "kustomize" mapping to URLs to fetch the binaries/source
# from. URLs are expected to be in go-getter format.
# (https://github.com/hashicorp/go-getter)
while IFS="" read -r line || [ -n "$line" ]
do
    fetch_requirement ${line%: *} ${line#*: }
done <${REQUIREMENTS_PATH}
